"use client";
import { createContext, ReactNode, useContext, useEffect, useMemo, useState } from "react";
type Item={id:string;name:string;option:string;price:number;quantity:number};
type Cart={items:Item[];open:boolean;add:(item:Omit<Item,"quantity">)=>void;remove:(id:string)=>void;setOpen:(value:boolean)=>void};
const CartContext=createContext<Cart | null>(null);
export function CartProvider({children}:{children:ReactNode}){const [items,setItems]=useState<Item[]>([]);const [open,setOpen]=useState(false);useEffect(()=>{const saved=localStorage.getItem("fr-cart");if(saved)setItems(JSON.parse(saved))},[]);useEffect(()=>{localStorage.setItem("fr-cart",JSON.stringify(items))},[items]);const value=useMemo<Cart>(()=>({items,open,setOpen,add:item=>{setItems(current=>{const found=current.find(x=>x.id===item.id);return found?current.map(x=>x.id===item.id?{...x,quantity:x.quantity+1}:x):[...current,{...item,quantity:1}]});setOpen(true)},remove:id=>setItems(current=>current.filter(x=>x.id!==id))}),[items,open]);return <CartContext.Provider value={value}>{children}<CartDrawer/></CartContext.Provider>}
export function useCart(){const cart=useContext(CartContext);if(!cart)throw new Error("CartProvider missing");return cart}
export function CartButton(){const {items,setOpen}=useCart();return <button className="cart-button" onClick={()=>setOpen(true)} aria-label="Open shopping bag">Bag <b>{items.reduce((sum,item)=>sum+item.quantity,0).toString().padStart(2,"0")}</b></button>}
function CartDrawer(){const {items,open,setOpen,remove}=useCart();const total=items.reduce((sum,item)=>sum+item.price*item.quantity,0);return <><button className={`cart-backdrop ${open?"visible":""}`} onClick={()=>setOpen(false)} aria-label="Close bag"/><aside className={`cart-drawer ${open?"open":""}`}><button className="cart-close" onClick={()=>setOpen(false)}>×</button><p className="eyebrow">YOUR SELECTIONS</p><h2>Shopping <em>bag.</em></h2>{items.length===0?<p className="cart-empty">Your bag is quiet.<br/>Find something worth keeping.</p>:<><div className="cart-items">{items.map(item=><div key={item.id}><div><b>{item.name}</b><small>{item.option} · ×{item.quantity}</small></div><span>${(item.price*item.quantity).toFixed(2)}</span><button onClick={()=>remove(item.id)}>×</button></div>)}</div><div className="cart-total"><span>Subtotal</span><b>${total.toFixed(2)}</b></div><button className="buy-button">Checkout <span>↗</span></button></>}</aside></>}
