"use client";
import { FormEvent,useEffect,useState } from "react";
type Discount={code:string;percent:number;active:boolean;uses:number;maxUses:number|null};
export default function DiscountManager(){const [discounts,setDiscounts]=useState<Discount[]>([]);const [code,setCode]=useState("");const [percent,setPercent]=useState("10");const [maxUses,setMaxUses]=useState("");const [notice,setNotice]=useState("");
 const load=async()=>{const response=await fetch("/api/owner/discounts",{cache:"no-store"});if(response.ok)setDiscounts((await response.json()).discounts)};useEffect(()=>{load()},[]);
 const save=async(event:FormEvent)=>{event.preventDefault();const response=await fetch("/api/owner/discounts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code,percent:Number(percent),maxUses:maxUses?Number(maxUses):null})});const data=await response.json();if(response.ok){setDiscounts(data.discounts);setCode("");setNotice("Discount code saved.")}else setNotice(data.error||"Could not save code.")};
 const toggle=async(item:Discount)=>{const response=await fetch("/api/owner/discounts",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:item.code,active:!item.active})});if(response.ok)setDiscounts((await response.json()).discounts)};
 const remove=async(item:Discount)=>{if(!window.confirm(`Delete discount ${item.code}?`))return;const response=await fetch("/api/owner/discounts",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({code:item.code})});if(response.ok)setDiscounts((await response.json()).discounts)};
 return <section className="discount-manager"><div className="owner-orders-heading"><div><p className="eyebrow">PROMOTIONS / CHECKOUT</p><h2>Discount codes.</h2></div></div>{notice&&<p className="status">{notice}</p>}<form onSubmit={save}><label>Code<input value={code} onChange={event=>setCode(event.target.value.toUpperCase().replace(/[^A-Z0-9_-]/g,""))} placeholder="SAVE10" minLength={2} maxLength={24} required/></label><label>Percentage off<input type="number" value={percent} onChange={event=>setPercent(event.target.value)} min="1" max="100" required/></label><label>Usage limit <small>optional</small><input type="number" value={maxUses} onChange={event=>setMaxUses(event.target.value)} min="1" placeholder="Unlimited"/></label><button>Create / update code</button></form><div className="discount-list">{discounts.length===0?<p>No discount codes yet.</p>:discounts.map(item=><article key={item.code}><div><b>{item.code}</b><small>{item.percent}% off · {item.uses} uses{item.maxUses!==null?` / ${item.maxUses}`:""}</small></div><span className={item.active?"active":"paused"}>{item.active?"ACTIVE":"PAUSED"}</span><button onClick={()=>toggle(item)}>{item.active?"Pause":"Activate"}</button><button onClick={()=>remove(item)}>Delete</button></article>)}</div></section>}
