"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import DiscountManager from "./discounts";
import ReviewManager from "./reviews";
type Item={name:string;option:string;unitPrice:number;quantity:number};type Message={id:number;sender:"customer"|"owner";body:string;createdAt:string};type Order={id:string;email:string;discordUsername:string;items:Item[];subtotal:number;status:string;createdAt:string;vouchedAt?:string;warrantyClaimedAt?:string;messages:Message[]};
const money=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(value);
export default function OwnerOrders(){
 const [orders,setOrders]=useState<Order[]>([]);const [open,setOpen]=useState<string>();const [drafts,setDrafts]=useState<Record<string,string>>({});const [error,setError]=useState("");const [query,setQuery]=useState("");const [statusFilter,setStatusFilter]=useState("all");
 const load=useCallback(async()=>{const response=await fetch("/api/owner/orders",{cache:"no-store"});if(response.ok)setOrders((await response.json()).orders)},[]);
 useEffect(()=>{load();const timer=setInterval(load,5000);return()=>clearInterval(timer)},[load]);
 const revenue=useMemo(()=>{const earned=orders.filter(order=>order.status==="paid"||order.status==="completed");const total=earned.reduce((sum,order)=>sum+order.subtotal,0);const pending=orders.filter(order=>order.status==="pending").reduce((sum,order)=>sum+order.subtotal,0);const completed=orders.filter(order=>order.status==="completed").length;return{total,pending,paidOrders:earned.length,completed,average:earned.length?total/earned.length:0}},[orders]);
 const filteredOrders=useMemo(()=>orders.filter(order=>{const haystack=`${order.id} ${order.email} ${order.discordUsername} ${order.items.map(item=>item.name).join(" ")}`.toLowerCase();return(statusFilter==="all"||order.status===statusFilter)&&haystack.includes(query.toLowerCase().trim())}),[orders,query,statusFilter]);
 const analytics=useMemo(()=>{const earned=orders.filter(order=>order.status==="paid"||order.status==="completed");const days=Array.from({length:7},(_,offset)=>{const date=new Date();date.setHours(0,0,0,0);date.setDate(date.getDate()-(6-offset));const key=date.toISOString().slice(0,10);return{key,label:date.toLocaleDateString(undefined,{weekday:"short"}),value:earned.filter(order=>order.createdAt.slice(0,10)===key).reduce((sum,order)=>sum+order.subtotal,0)}});const products=new Map<string,number>();for(const order of earned)for(const item of order.items)products.set(item.name,(products.get(item.name)||0)+item.quantity);const top=[...products.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5);return{days,top,maxDay:Math.max(1,...days.map(day=>day.value)),maxProduct:Math.max(1,...top.map(item=>item[1]))}},[orders]);
 const status=async(id:string,value:string)=>{const response=await fetch("/api/owner/orders",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status:value})});const data=await response.json();if(response.ok)setOrders(data.orders);else setError(data.error||"Status update failed.")};
 const remove=async(id:string)=>{if(!window.confirm(`Permanently delete ${id} and its entire chat?`))return;const response=await fetch("/api/owner/orders",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});const data=await response.json();if(response.ok){setOrders(data.orders);setOpen(undefined)}else setError(data.error||"Delete failed.")};
 const send=async(event:FormEvent,id:string)=>{event.preventDefault();const body=drafts[id]?.trim();if(!body)return;const response=await fetch(`/api/owner/orders/${encodeURIComponent(id)}/messages`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({body})});const data=await response.json();if(response.ok){setOrders(data.orders);setDrafts(value=>({...value,[id]:""}))}else setError(data.error||"Message failed.")};
 return <section className="owner-orders">
  <div className="revenue-heading"><div><p className="eyebrow">PRIVATE / REVENUE</p><h2>Your earnings.</h2></div><small>Paid + completed orders</small></div>
  <div className="revenue-grid"><article className="revenue-total"><span>Total revenue</span><strong>{money(revenue.total)}</strong><small>Money marked paid or completed</small></article><article><span>Pending revenue</span><strong>{money(revenue.pending)}</strong><small>Waiting for payment</small></article><article><span>Paid orders</span><strong>{revenue.paidOrders}</strong><small>{revenue.completed} completed</small></article><article><span>Average sale</span><strong>{money(revenue.average)}</strong><small>Per paid order</small></article></div>
  <section className="sales-analytics"><div><p className="eyebrow">LAST 7 DAYS</p><h3>Revenue trend.</h3><div className="bar-chart">{analytics.days.map(day=><article key={day.key}><b>{day.value?money(day.value):"$0"}</b><i style={{height:`${Math.max(4,day.value/analytics.maxDay*100)}%`}}/><span>{day.label}</span></article>)}</div></div><div><p className="eyebrow">BEST SELLERS</p><h3>Top products.</h3><div className="product-bars">{analytics.top.length?analytics.top.map(([name,count])=><article key={name}><span>{name}</span><i><b style={{width:`${count/analytics.maxProduct*100}%`}}/></i><em>{count}</em></article>):<p>No paid sales yet.</p>}</div></div></section>
  <div className="security-tools"><div><b>Protected owner access</b><small>2-hour sessions · brute-force lockout</small></div><a href="/api/owner/backup" download>Download database backup</a></div>
  <DiscountManager/>
  <ReviewManager/>
  <div className="owner-orders-heading"><div><p className="eyebrow">ORDERS / PRIVATE CHAT</p><h2>Customer orders.</h2></div><button onClick={load}>Refresh</button></div><div className="order-filters"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search ID, email, Discord, or product"/><select value={statusFilter} onChange={event=>setStatusFilter(event.target.value)}><option value="all">All statuses</option><option value="pending">Pending</option><option value="paid">Paid</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="closed">Closed</option></select></div>{error&&<div className="status">{error}</div>}{filteredOrders.length===0?<p className="orders-empty">No matching orders.</p>:<div className="orders-list">{filteredOrders.map(order=><article key={order.id}><button className="order-summary" onClick={()=>setOpen(open===order.id?undefined:order.id)}><span><small>{new Date(order.createdAt).toLocaleString()}</small><b>{order.id}</b><em>{order.email} · Discord: {order.discordUsername||"Not provided"}</em></span><strong>{money(order.subtotal)}</strong><i className={order.status}>{order.status}</i></button>{open===order.id&&<div className="owner-order-detail">{(order.vouchedAt||order.warrantyClaimedAt)&&<div className="owner-coverage"><span>{order.vouchedAt?"✓ Vouched":"Not vouched"}</span>{order.warrantyClaimedAt&&<b>Warranty claim open</b>}</div>}<div className="owner-order-items">{order.items.map((item,index)=><p key={index}><span>{item.name} · {item.option} ×{item.quantity}</span><b>{money(item.unitPrice*item.quantity)}</b></p>)}</div><label>Order status<select value={order.status} onChange={event=>status(order.id,event.target.value)}><option value="pending">Pending payment</option><option value="paid">Paid</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="closed">Close and hide from customer</option></select></label><button className="delete-order" type="button" onClick={()=>remove(order.id)}>Delete order permanently</button><div className="owner-messages">{order.messages.length===0?<p>No messages yet.</p>:order.messages.map(message=><div className={message.sender} key={message.id}><b>{message.sender==="owner"?"YOU":"CUSTOMER"}</b><p>{message.body}</p><small>{new Date(message.createdAt).toLocaleString()}</small></div>)}</div>{order.status!=="closed"&&<form onSubmit={event=>send(event,order.id)}><textarea placeholder="Reply privately…" maxLength={2000} value={drafts[order.id]||""} onChange={event=>setDrafts(value=>({...value,[order.id]:event.target.value}))}/><button>Send reply</button></form>}</div>}</article>)}</div>}
 </section>
}
