"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { categories, Product } from "../catalog";
import OwnerOrders from "./orders";
type Inventory=Record<string,number>;type ProductEdit={name:string;description:string;imageUrl?:string};type Store={prices:Record<string,number>;productEdits:Record<string,ProductEdit>;customProducts:(Product&{category:string})[]};
const key=(category:string,product:string)=>`${category}/${product}`;const priceKey=(category:string,product:string,option:number)=>`${category}/${product}/${option}`;
export default function OwnerPanel(){const [username,setUsername]=useState("");const [password,setPassword]=useState("");const [message,setMessage]=useState("");const [loggedIn,setLoggedIn]=useState(false);const [inventory,setInventory]=useState<Inventory>({});const [store,setStore]=useState<Store>({prices:{},productEdits:{},customProducts:[]});const [amounts,setAmounts]=useState<Record<string,string>>({});const [edits,setEdits]=useState<Record<string,string>>({});const [productEdits,setProductEdits]=useState<Record<string,ProductEdit>>({});const [newProduct,setNewProduct]=useState({category:"discord-boost",name:"",description:"",price:""});
 const load=async()=>{const [inventoryResult,storeResult]=await Promise.all([fetch("/api/inventory",{cache:"no-store"}),fetch("/api/storefront",{cache:"no-store"})]);setInventory(await inventoryResult.json());setStore(await storeResult.json())};useEffect(()=>{load();fetch("/api/owner/login",{cache:"no-store"}).then(response=>response.json()).then(data=>{if(data.authenticated)setLoggedIn(true)}).catch(()=>{})},[]);
 const products=useMemo(()=>categories.flatMap(category=>[...category.products,...store.customProducts.filter(product=>product.category===category.slug)].map(product=>{const saved=store.productEdits?.[key(category.slug,product.slug)];return{category,product:{...product,...saved}}})),[store]);
 const login=async(e:FormEvent)=>{e.preventDefault();setMessage("");const config=await fetch("/api/owner/login",{cache:"no-store"}).then(r=>r.json()).catch(()=>({twoFactorEnabled:false}));const otp=config.twoFactorEnabled?window.prompt("Enter the 6-digit code from your authenticator app")||"":"";if(config.twoFactorEnabled&&!otp)return;const r=await fetch("/api/owner/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,password,otp})});const data=await r.json().catch(()=>({}));if(r.ok){setLoggedIn(true);setPassword("");setMessage("Owner access unlocked.");await load()}else setMessage(data.error||"Invalid owner credentials.")};
 const update=async(productKey:string,sign:number)=>{const count=Number(amounts[productKey]);if(!Number.isInteger(count)||count<1){setMessage("Enter a whole number before updating stock.");return}const r=await fetch("/api/inventory",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({key:productKey,delta:sign*count})});if(r.ok){const data=await r.json();setInventory(v=>({...v,[productKey]:data.stock}));setAmounts(v=>({...v,[productKey]:""}));setMessage("Stock updated.")}else setMessage("Could not update stock.")};
 const savePrice=async(id:string)=>{const price=Number(edits[id]);if(!Number.isFinite(price)||price<0){setMessage("Enter a valid price.");return}const r=await fetch("/api/storefront",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({key:id,price})});if(r.ok){setStore(await r.json());setMessage("Price updated.")}else setMessage("Could not save that price.")};
 const saveProduct=async(productKey:string,current:ProductEdit)=>{const value=productEdits[productKey]||current;const r=await fetch("/api/storefront",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"product",key:productKey,...value})});if(r.ok){setStore(await r.json());setMessage("Product updated.")}else setMessage((await r.json().catch(()=>({}))).error||"Could not update that product.")};
 const addProduct=async(e:FormEvent)=>{e.preventDefault();const price=Number(newProduct.price);if(!newProduct.name.trim()||!newProduct.description.trim()||!Number.isFinite(price)){setMessage("Complete the new product fields.");return}const r=await fetch("/api/storefront",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...newProduct,price})});if(r.ok){setStore(await r.json());setNewProduct({category:"discord-boost",name:"",description:"",price:""});setMessage("Product added.");await load()}else setMessage((await r.json().catch(()=>({}))).error||"Could not add product.")};
 if(!loggedIn)return <main className="owner-page"><nav className="nav"><Link href="/" className="wordmark"><span>FR</span> FOREVERREPENT</Link><span className="owner-pill">OWNER ACCESS</span></nav><form className="login-card" onSubmit={login}><p className="eyebrow">PRIVATE / OWNER ONLY</p><h1>Welcome <em>back.</em></h1><p>Sign in to manage products, inventory, orders, and private chats.</p><label>Username<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{message&&<small>{message}</small>}<button className="buy-button">Login <span>↗</span></button><Link href="/">← Back to storefront</Link></form></main>;
 return <main className="owner-page"><nav className="nav"><Link href="/" className="wordmark"><span>FR</span> FOREVERREPENT</Link><button className="nav-discord" onClick={async()=>{await fetch("/api/owner/logout",{method:"POST"});setLoggedIn(false)}}>Log out</button></nav><section className="owner-content"><p className="eyebrow">OWNER PANEL / LIVE STORE</p><h1>Store <em>control.</em></h1><p>Manage customer orders, private chats, products, prices, and stock.</p>{message&&<div className="status">{message}</div>}<OwnerOrders/><form className="add-product" onSubmit={addProduct}><h2>Add product</h2><select value={newProduct.category} onChange={e=>setNewProduct(v=>({...v,category:e.target.value}))}>{categories.map(category=><option key={category.slug} value={category.slug}>{category.title}</option>)}</select><input placeholder="Product name" value={newProduct.name} onChange={e=>setNewProduct(v=>({...v,name:e.target.value}))}/><input placeholder="Short description" value={newProduct.description} onChange={e=>setNewProduct(v=>({...v,description:e.target.value}))}/><input inputMode="decimal" placeholder="Price" value={newProduct.price} onChange={e=>setNewProduct(v=>({...v,price:e.target.value}))}/><button>Add product</button></form><div className="stock-list">{products.map(({category,product})=>{const productKey=key(category.slug,product.slug);const productCopy=productEdits[productKey]||{name:product.name,description:product.description};return <div className="stock-row expanded" key={productKey}><div><small>{category.title}</small><div className="product-editor"><input aria-label={`${product.name} name`} value={productCopy.name} onChange={e=>setProductEdits(v=>({...v,[productKey]:{...productCopy,name:e.target.value}}))}/><textarea aria-label={`${product.name} description`} value={productCopy.description} onChange={e=>setProductEdits(v=>({...v,[productKey]:{...productCopy,description:e.target.value}}))}/><button type="button" onClick={()=>saveProduct(productKey,{name:product.name,description:product.description})}>Save product</button></div>{product.options.map((option,index)=>{const id=priceKey(category.slug,product.slug,index);const price=store.prices[id]??option.price;return <div className="price-editor" key={id}><span>{option.label}</span><input inputMode="decimal" value={edits[id]??String(price)} onChange={e=>setEdits(v=>({...v,[id]:e.target.value}))}/><button type="button" onClick={()=>savePrice(id)}>Save price</button></div>})}</div><b>{inventory[productKey]??"—"}<small> in stock</small></b><div className="stock-actions"><button type="button" onClick={()=>update(productKey,-1)}>OUT</button><input inputMode="numeric" placeholder="#" value={amounts[productKey]||""} onChange={e=>setAmounts(v=>({...v,[productKey]:e.target.value.replace(/\D/g,"")}))}/><button type="button" onClick={()=>update(productKey,1)}>IN</button></div></div>})}</div></section></main>}
