"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { categories } from "../catalog";
type Inventory = Record<string, number>;
const key=(category:string,product:string)=>`${category}/${product}`;
export default function OwnerPanel(){const [username,setUsername]=useState("");const [password,setPassword]=useState("");const [message,setMessage]=useState("");const [loggedIn,setLoggedIn]=useState(false);const [inventory,setInventory]=useState<Inventory>({});const [amounts,setAmounts]=useState<Record<string,string>>({});
 const load=async()=>{const result=await fetch("/api/inventory",{cache:"no-store"});setInventory(await result.json())};useEffect(()=>{load()},[]);
 const login=async(e:FormEvent)=>{e.preventDefault();setMessage("");const r=await fetch("/api/owner/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,password})});if(r.ok){setLoggedIn(true);setPassword("");setMessage("Owner access unlocked.")}else setMessage("Invalid owner credentials.")};
 const update=async(productKey:string,sign:number)=>{const count=Number(amounts[productKey]);if(!Number.isInteger(count)||count<1){setMessage("Enter a whole number before updating stock.");return}const r=await fetch("/api/inventory",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({key:productKey,delta:sign*count})});if(r.ok){const data=await r.json();setInventory(v=>({...v,[productKey]:data.stock}));setAmounts(v=>({...v,[productKey]:""}));setMessage("Stock updated on the live storefront.")}else setMessage("Could not update stock.")};
 if(!loggedIn)return <main className="owner-page"><nav className="nav"><Link href="/" className="wordmark"><span>FR</span> FOREVERREPENT</Link><span className="owner-pill">OWNER ACCESS</span></nav><form className="login-card" onSubmit={login}><p className="eyebrow">PRIVATE / OWNER ONLY</p><h1>Welcome <em>back.</em></h1><p>Sign in to manage marketplace inventory.</p><label>Username<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{message&&<small>{message}</small>}<button className="buy-button">Login <span>↗</span></button><Link href="/">← Back to storefront</Link></form></main>;
 return <main className="owner-page"><nav className="nav"><Link href="/" className="wordmark"><span>FR</span> FOREVERREPENT</Link><button className="nav-discord" onClick={async()=>{await fetch("/api/owner/logout",{method:"POST"});setLoggedIn(false)}}>Log out</button></nav><section className="owner-content"><p className="eyebrow">OWNER PANEL / LIVE INVENTORY</p><h1>Stock <em>control.</em></h1><p>Use IN or OUT to adjust the number shown on every live product card.</p>{message&&<div className="status">{message}</div>}<div className="stock-list">{categories.flatMap(category=>category.products.map(product=>{const productKey=key(category.slug,product.slug);return <div className="stock-row" key={productKey}><div><small>{category.title}</small><h2>{product.name}</h2></div><b>{inventory[productKey]??"—"}<small> in stock</small></b><div className="stock-actions"><button onClick={()=>update(productKey,-1)}>OUT</button><input inputMode="numeric" placeholder="#" value={amounts[productKey]||""} onChange={e=>setAmounts(v=>({...v,[productKey]:e.target.value.replace(/\D/g,"")}))}/><button onClick={()=>update(productKey,1)}>IN</button></div></div>}))}</div></section></main>}
