"use client";
import { createContext, FormEvent, ReactNode, useContext, useEffect, useMemo, useState } from "react";
import Link from "next/link";
type Item={id:string;name:string;option:string;price:number;quantity:number};
type Cart={items:Item[];open:boolean;add:(item:Omit<Item,"quantity">)=>void;remove:(id:string)=>void;clear:()=>void;setOpen:(value:boolean)=>void};
const CartContext=createContext<Cart|null>(null);
export function CartProvider({children}:{children:ReactNode}){const [items,setItems]=useState<Item[]>([]);const [open,setOpen]=useState(false);useEffect(()=>{try{const saved=localStorage.getItem("fr-cart");if(saved)setItems(JSON.parse(saved))}catch{}},[]);useEffect(()=>{localStorage.setItem("fr-cart",JSON.stringify(items))},[items]);const value=useMemo<Cart>(()=>({items,open,setOpen,clear:()=>setItems([]),add:item=>{setItems(current=>{const found=current.find(x=>x.id===item.id);return found?current.map(x=>x.id===item.id?{...x,quantity:x.quantity+1}:x):[...current,{...item,quantity:1}]});setOpen(true)},remove:id=>setItems(current=>current.filter(x=>x.id!==id))}),[items,open]);return <CartContext.Provider value={value}>{children}<CartDrawer/></CartContext.Provider>}
export function useCart(){const cart=useContext(CartContext);if(!cart)throw new Error("CartProvider missing");return cart}
export function CartButton(){const {items,setOpen}=useCart();return <><Link className="orders-link" href="/orders">My orders</Link><button className="cart-button" onClick={()=>setOpen(true)} aria-label="Open shopping bag">Bag <b>{items.reduce((sum,item)=>sum+item.quantity,0).toString().padStart(2,"0")}</b></button></>}
function CartDrawer(){const {items,open,setOpen,remove,clear}=useCart();const [checkout,setCheckout]=useState(false);const [email,setEmail]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(false);const total=items.reduce((sum,item)=>sum+item.price*item.quantity,0);
 const submit=async(event:FormEvent)=>{event.preventDefault();setLoading(true);setError("");try{const response=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,items:items.map(({id,option,quantity})=>({id,option,quantity}))})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Checkout failed.");try{const saved=JSON.parse(localStorage.getItem("fr-orders")||"[]");localStorage.setItem("fr-orders",JSON.stringify([data.order.id,...saved.filter((id:string)=>id!==data.order.id)].slice(0,50)))}catch{}clear();window.location.href=`/order/${data.order.id}`}catch(reason){setError(reason instanceof Error?reason.message:"Checkout failed.");setLoading(false)}};
 return <><button className={`cart-backdrop ${open?"visible":""}`} onClick={()=>setOpen(false)} aria-label="Close bag"/><aside className={`cart-drawer ${open?"open":""}`}><button className="cart-close" onClick={()=>setOpen(false)}>×</button><p className="eyebrow">YOUR SELECTIONS</p><h2>Shopping <em>bag.</em></h2>{items.length===0?<p className="cart-empty">Your bag is quiet.<br/>Find something worth keeping.</p>:<>{!checkout?<><div className="cart-items">{items.map(item=><div key={item.id}><div><b>{item.name}</b><small>{item.option} · ×{item.quantity}</small></div><span>${(item.price*item.quantity).toFixed(2)}</span><button onClick={()=>remove(item.id)}>×</button></div>)}</div><div className="cart-total"><span>Subtotal</span><b>${total.toFixed(2)}</b></div><button className="buy-button" onClick={()=>setCheckout(true)}>Checkout <span>↗</span></button></>:<form className="checkout-form" onSubmit={submit}><button type="button" className="checkout-back" onClick={()=>setCheckout(false)}>← Back to bag</button><h3>Create your invoice.</h3><p>Enter your email. Payment will be arranged privately through Discord.</p><label>Email address<input type="email" value={email} onChange={event=>setEmail(event.target.value)} autoComplete="email" required placeholder="you@example.com"/></label><div className="invoice-preview"><span>Invoice total</span><b>${total.toFixed(2)}</b></div>{error&&<small className="checkout-error">{error}</small>}<button className="buy-button" disabled={loading}>{loading?"Creating order…":"Create order & invoice"}<span>↗</span></button><small>Your private order access stays secured to this browser.</small></form>}</>}</aside></>}
