export type Product = { slug: string; name: string; description: string; options: { label: string; price: number; note?: string }[] };
export type Category = { slug: string; nav: string; title: string; kicker: string; summary: string; icon: string; products: Product[] };
export const categories: Category[] = [
 {slug:"discord-boost",nav:"Discord Boosts",title:"Discord Boosts",kicker:"SERVER POWER",summary:"Boost your space and unlock its full potential.",icon:"✦",products:[{slug:"discord-boost",name:"Discord Boost",description:"Choose the boost quantity your server needs. Every option is a one-time purchase.",options:[{label:"8 boosts",price:6.50,note:"One-time purchase"},{label:"10 boosts",price:8,note:"One-time purchase"},{label:"12 boosts",price:9.50,note:"One-time purchase"},{label:"14 boosts",price:11,note:"One-time purchase"}]}]},
 {slug:"music",nav:"Music",title:"Music Accounts",kicker:"LIFETIME ACCESS",summary:"Keep your soundtrack close, permanently.",icon:"♫",products:[{slug:"spotify",name:"Spotify",description:"Lifetime-owned music account with a personal listening space.",options:[{label:"Lifetime account",price:15.99,note:"Owned account · no renewal"}]},{slug:"apple-music",name:"Apple Music",description:"Your music, available when you need it.",options:[{label:"Lifetime account",price:17.99,note:"Owned account · no renewal"}]},{slug:"deezer",name:"Deezer",description:"A full library for the music you keep returning to.",options:[{label:"Lifetime account",price:12.99,note:"Owned account · no renewal"}]},{slug:"youtube",name:"YouTube",description:"A focused, uninterrupted way to watch and listen.",options:[{label:"Lifetime account",price:18.99,note:"Owned account · no renewal"}]}]},
 {slug:"vpn",nav:"VPNs",title:"VPNs",kicker:"LIFETIME ACCESS",summary:"More privacy, fewer distractions.",icon:"◈",products:[{slug:"nordvpn",name:"NordVPN",description:"Private routing for a more considered online life.",options:[{label:"Lifetime account",price:23.99,note:"No renewal"}]},{slug:"ipvanish",name:"IPVanish",description:"Stay covered wherever you connect.",options:[{label:"Lifetime account",price:20.99,note:"No renewal"}]},{slug:"expressvpn",name:"ExpressVPN",description:"Private access with a premium footprint.",options:[{label:"Lifetime account",price:29.99,note:"No renewal"}]},{slug:"tunnelbear",name:"TunnelBear",description:"Simple, private browsing for everyday use.",options:[{label:"Lifetime account",price:18.99,note:"No renewal"}]},{slug:"mullvad",name:"Mullvad VPN",description:"A minimalist privacy option.",options:[{label:"Lifetime account",price:25.99,note:"No renewal"}]}]},
 {slug:"streaming",nav:"Streaming",title:"Streaming",kicker:"LIFETIME ACCESS",summary:"Keep every screen ready for your next session.",icon:"▸",products:[{slug:"netflix",name:"Netflix",description:"Shows and films for the nights you stay in.",options:[{label:"Lifetime account",price:15.99,note:"No renewal"}]},{slug:"crunchyroll",name:"Crunchyroll",description:"Your anime queue, always open.",options:[{label:"Lifetime account",price:13.49,note:"No renewal"}]},{slug:"paramount-plus",name:"Paramount+",description:"A considered collection of stories and live moments.",options:[{label:"Lifetime account",price:11.99,note:"No renewal"}]},{slug:"hbo-max",name:"HBO Max",description:"Premium series and films at your fingertips.",options:[{label:"Lifetime account",price:15.99,note:"No renewal"}]},{slug:"amc-plus",name:"AMC+",description:"Stories with an edge.",options:[{label:"Lifetime account",price:11.99,note:"No renewal"}]},{slug:"disney-plus",name:"Disney+",description:"A complete family watchlist.",options:[{label:"Lifetime account",price:14.49,note:"No renewal"}]},{slug:"prime-video",name:"Prime Video",description:"A wide screen for every mood.",options:[{label:"Lifetime account",price:14.49,note:"No renewal"}]},{slug:"dazn",name:"DAZN",description:"The live sports schedule, simplified.",options:[{label:"Lifetime account",price:23.99,note:"No renewal"}]},{slug:"ufc",name:"UFC",description:"Fight nights, on demand.",options:[{label:"Lifetime account",price:26.99,note:"No renewal"}]},{slug:"nba-league-pass",name:"NBA League Pass",description:"Every court, all season long.",options:[{label:"Lifetime account",price:29.99,note:"No renewal"}]}]}
];
export const getCategory=(slug:string)=>categories.find(c=>c.slug===slug);
export const getProduct=(category:string,product:string)=>getCategory(category)?.products.find(p=>p.slug===product);
