// Product catalog with branded artwork enabled.
export type Product = { slug: string; name: string; description: string; options: { label: string; price: number; note?: string }[] };
export type Category = { slug: string; nav: string; title: string; kicker: string; summary: string; icon: string; products: Product[] };
export const categories: Category[] = [
 {slug:"discord-boost",nav:"Discord Boosts",title:"Discord Boosts",kicker:"SERVER POWER",summary:"Boost your space and unlock its full potential.",icon:"✦",products:[{slug:"discord-boost",name:"Discord Boost",description:"Choose the one-month boost quantity your server needs.",options:[{label:"8 boosts",price:6.50,note:"1 month"},{label:"10 boosts",price:8,note:"1 month"},{label:"14 boosts",price:10.50,note:"1 month"},{label:"16 boosts",price:12,note:"1 month"},{label:"18 boosts",price:13.50,note:"1 month"},{label:"20 boosts",price:15,note:"1 month"},{label:"28 boosts",price:20,note:"1 month"},{label:"30 boosts",price:22,note:"1 month"}]}]},
 {slug:"music",nav:"Music",title:"Music Accounts",kicker:"LIFETIME ACCESS",summary:"Keep your soundtrack close, permanently.",icon:"♫",products:[{slug:"spotify",name:"Spotify",description:"Lifetime-owned music account with a personal listening space.",options:[{label:"Lifetime account",price:3,note:"Owned account · no renewal"}]},{slug:"apple-music",name:"Apple Music",description:"Your music, available when you need it.",options:[{label:"Lifetime account",price:3,note:"Owned account · no renewal"}]},{slug:"deezer",name:"Deezer",description:"A full library for the music you keep returning to.",options:[{label:"Lifetime account",price:2,note:"Owned account · no renewal"}]},{slug:"youtube",name:"YouTube",description:"A focused, uninterrupted way to watch and listen.",options:[{label:"Lifetime account",price:3,note:"Owned account · no renewal"}]}]},
 {slug:"vpn",nav:"VPNs",title:"VPNs",kicker:"LIFETIME ACCESS",summary:"More privacy, fewer distractions.",icon:"◈",products:[{slug:"nordvpn",name:"NordVPN",description:"Private routing for a more considered online life.",options:[{label:"Lifetime account",price:3.50,note:"No renewal"}]},{slug:"ipvanish",name:"IPVanish",description:"Stay covered wherever you connect.",options:[{label:"Lifetime account",price:2,note:"No renewal"}]},{slug:"expressvpn",name:"ExpressVPN",description:"Private access with a premium footprint.",options:[{label:"Lifetime account",price:2,note:"No renewal"}]},{slug:"tunnelbear",name:"TunnelBear",description:"Simple, private browsing for everyday use.",options:[{label:"Lifetime account",price:2,note:"No renewal"}]},{slug:"mullvad",name:"Mullvad VPN",description:"A minimalist privacy option.",options:[{label:"Lifetime account",price:3.50,note:"No renewal"}]}]},
 {slug:"streaming",nav:"Streaming",title:"Streaming",kicker:"LIFETIME ACCESS",summary:"Keep every screen ready for your next session.",icon:"▸",products:[{slug:"netflix",name:"Netflix",description:"Shows and films for the nights you stay in.",options:[{label:"Lifetime account",price:2,note:"No renewal"}]},{slug:"crunchyroll",name:"Crunchyroll",description:"Your anime queue, always open.",options:[{label:"Lifetime account",price:2,note:"No renewal"}]},{slug:"paramount-plus",name:"Paramount+",description:"A considered collection of stories and live moments.",options:[{label:"Lifetime account",price:2,note:"No renewal"}]},{slug:"hbo-max",name:"HBO Max",description:"Premium series and films at your fingertips.",options:[{label:"Lifetime account",price:2,note:"No renewal"}]},{slug:"amc-plus",name:"AMC+",description:"Stories with an edge.",options:[{label:"Lifetime account",price:2,note:"No renewal"}]},{slug:"disney-plus",name:"Disney+",description:"A complete family watchlist.",options:[{label:"Lifetime account",price:2,note:"No renewal"}]},{slug:"prime-video",name:"Prime Video",description:"A wide screen for every mood.",options:[{label:"Lifetime account",price:2,note:"No renewal"}]},{slug:"dazn",name:"DAZN",description:"The live sports schedule, simplified.",options:[{label:"Lifetime account",price:2,note:"No renewal"}]},{slug:"ufc",name:"UFC",description:"Fight nights, on demand.",options:[{label:"Lifetime account",price:2,note:"No renewal"}]},{slug:"nba-league-pass",name:"NBA League Pass",description:"Every court, all season long.",options:[{label:"Lifetime account",price:2,note:"No renewal"}]}]},
 {slug:"web-services",nav:"Web Services",title:"Web Services",kicker:"LIFETIME ACCESS",summary:"Launch with the tools to build your place online.",icon:"⌘",products:[{slug:"website-builder",name:"Website Builder Account",description:"A lifetime account for building and publishing your own website.",options:[{label:"Lifetime account",price:5,note:"Owned account · no renewal"}]}]}
];
export const getCategory=(slug:string)=>categories.find(c=>c.slug===slug);
export const getProduct=(category:string,product:string)=>getCategory(category)?.products.find(p=>p.slug===product);
