export type Product = { slug: string; name: string; description: string; options: { label: string; price: number; note?: string }[] };
export type Category = { slug: string; nav: string; title: string; kicker: string; summary: string; icon: string; products: Product[] };
export const categories: Category[] = [
 {slug:"discord-boost",nav:"Discord Boosts",title:"Discord Boosts",kicker:"SERVER POWER",summary:"Boost your space and unlock its full potential.",icon:"✦",products:[{slug:"discord-boost",name:"Discord Boost",description:"Support your server with a clean, reliable boost package.",options:[{label:"1 month",price:7.99,note:"One server boost · 30 days"},{label:"3 months",price:20.99,note:"One server boost · 90 days"}]}]},
 {slug:"music",nav:"Music",title:"Music Accounts",kicker:"LIFETIME ACCESS",summary:"Keep your soundtrack close, permanently.",icon:"♫",products:[{slug:"spotify",name:"Spotify",description:"Lifetime-owned music account with a personal listening space.",options:[{label:"Lifetime account",price:15.99,note:"Owned account · no renewal"}]},{slug:"apple-music",name:"Apple Music",description:"Your music, available when you need it.",options:[{label:"Lifetime account",price:17.99,note:"Owned account · no renewal"}]},{slug:"deezer",name:"Deezer",description:"A full library for the music you keep returning to.",options:[{label:"Lifetime account",price:12.99,note:"Owned account · no renewal"}]},{slug:"youtube",name:"YouTube",description:"A focused, uninterrupted way to watch and listen.",options:[{label:"Lifetime account",price:18.99,note:"Owned account · no renewal"}]}]},
 {slug:"vpn",nav:"VPNs",title:"VPNs",kicker:"PRIVATE ROUTING",summary:"More privacy, fewer distractions.",icon:"◈",products:[{slug:"nordvpn",name:"NordVPN",description:"Private routing for a more considered online life.",options:[{label:"1 month",price:4.99},{label:"1 year",price:23.99}]},{slug:"ipvanish",name:"IPVanish",description:"Stay covered wherever you connect.",options:[{label:"1 month",price:4.49},{label:"1 year",price:20.99}]},{slug:"expressvpn",name:"ExpressVPN",description:"Private access with a premium footprint.",options:[{label:"1 month",price:5.99},{label:"1 year",price:29.99}]},{slug:"tunnelbear",name:"TunnelBear",description:"Simple, private browsing for everyday use.",options:[{label:"1 month",price:3.99},{label:"1 year",price:18.99}]},{slug:"mullvad",name:"Mullvad VPN",description:"A minimalist privacy option.",options:[{label:"1 month",price:5.49},{label:"1 year",price:25.99}]}]},
 {slug:"streaming",nav:"Streaming",title:"Streaming",kicker:"WATCH LIST",summary:"Keep every screen ready for your next session.",icon:"▸",products:[{slug:"netflix",name:"Netflix",description:"Shows and films for the nights you stay in.",options:[{label:"1 month",price:5.99},{label:"3 months",price:15.99}]},{slug:"crunchyroll",name:"Crunchyroll",description:"Your anime queue, always open.",options:[{label:"1 month",price:4.99},{label:"3 months",price:13.49}]},{slug:"paramount-plus",name:"Paramount+",description:"A considered collection of stories and live moments.",options:[{label:"1 month",price:4.49},{label:"3 months",price:11.99}]},{slug:"hbo-max",name:"HBO Max",description:"Premium series and films at your fingertips.",options:[{label:"1 month",price:5.99},{label:"3 months",price:15.99}]},{slug:"amc-plus",name:"AMC+",description:"Stories with an edge.",options:[{label:"1 month",price:4.49},{label:"3 months",price:11.99}]},{slug:"disney-plus",name:"Disney+",description:"A complete family watchlist.",options:[{label:"1 month",price:5.49},{label:"3 months",price:14.49}]},{slug:"prime-video",name:"Prime Video",description:"A wide screen for every mood.",options:[{label:"1 month",price:5.49},{label:"3 months",price:14.49}]},{slug:"dazn",name:"DAZN",description:"The live sports schedule, simplified.",options:[{label:"1 month",price:8.99},{label:"3 months",price:23.99}]},{slug:"ufc",name:"UFC",description:"Fight nights, on demand.",options:[{label:"1 month",price:9.99},{label:"3 months",price:26.99}]},{slug:"nba-league-pass",name:"NBA League Pass",description:"Every court, all season long.",options:[{label:"1 month",price:10.99},{label:"3 months",price:29.99}]}]}
];
export const getCategory=(slug:string)=>categories.find(c=>c.slug===slug);
export const getProduct=(category:string,product:string)=>getCategory(category)?.products.find(p=>p.slug===product);
