"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { categories } from "./catalog";
type Sale={product:string;completedAt:string};
type Review={product:string;rating:number;review:string;createdAt:string};
const featured=categories.flatMap(category=>category.products.slice(0,1).map(product=>({category,product}))).slice(0,4);
export default function TrustSections(){const [sales,setSales]=useState<Sale[]>([]);const [reviews,setReviews]=useState<Review[]>([]);useEffect(()=>{fetch("/api/storefront",{cache:"no-store"}).then(r=>r.json()).then(data=>{setSales(data.sales||[]);setReviews(data.reviews||[])}).catch(()=>{})},[]);return <>
 <section className="featured-section"><div className="section-heading"><p className="eyebrow">POPULAR PICKS</p><h2>Featured <em>products.</em></h2></div><div className="featured-grid">{featured.map(({category,product})=><Link href={`/${category.slug}/${product.slug}`} key={`${category.slug}/${product.slug}`}><small>{category.title}</small><h3>{product.name}</h3><p>{product.description}</p><span>View product →</span></Link>)}</div></section>
 <section className="process-section"><div className="section-heading"><p className="eyebrow">SIMPLE / PRIVATE / TRACKED</p><h2>How it <em>works.</em></h2></div><div className="process-grid"><article><b>01</b><h3>Choose</h3><p>Pick a product and checkout with your email and Discord username.</p></article><article><b>02</b><h3>Pay</h3><p>Use the private order chat to arrange payment directly with the owner.</p></article><article><b>03</b><h3>Receive</h3><p>Your order stays saved with its status, invoice, support chat, and Order ID.</p></article><article><b>04</b><h3>Vouch</h3><p>Vouch after completion to activate your one-month warranty coverage.</p></article></div></section>
 {sales.length>0&&<section className="sales-section"><div><p className="eyebrow">RECENT VERIFIED SALES</p><h2>People are <em>shopping.</em></h2></div><div className="sales-list">{sales.map((sale,index)=><article key={`${sale.completedAt}-${index}`}><i/><span><b>{sale.product}</b><small>Completed {new Date(sale.completedAt).toLocaleDateString()}</small></span><em>VERIFIED</em></article>)}</div></section>}
 {reviews.length>0&&<section className="reviews-section"><div className="section-heading"><p className="eyebrow">CUSTOMER VOUCHES</p><h2>Real buyers. <em>Real reviews.</em></h2></div><div className="reviews-grid">{reviews.map((review,index)=><article key={`${review.createdAt}-${index}`}><div><b>{"★".repeat(review.rating)}</b><small>VERIFIED PURCHASE</small></div><p>“{review.review}”</p><span>{review.product} · {new Date(review.createdAt).toLocaleDateString()}</span></article>)}</div></section>}
 <section className="faq-section"><div className="section-heading"><p className="eyebrow">STORE FAQ</p><h2>Good to <em>know.</em></h2></div><div className="faq-list"><details><summary>How do I receive my product?</summary><p>After checkout, use your private order chat to arrange payment and delivery with the owner.</p></details><details><summary>How does the warranty work?</summary><p>Completed orders receive a one-month warranty only after the customer submits a vouch. No vouch means no warranty coverage.</p></details><details><summary>Where can I find my order?</summary><p>Your Order ID and private order page are saved in My Orders on the same browser used at checkout.</p></details><details><summary>Can I request something not listed?</summary><p>Yes. Contact foreverrepent. through Discord for private or custom requests.</p></details></div><Link className="terms-link" href="/terms">Read store terms and warranty policy →</Link></section>
 </>}
