"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Category, Product } from "../../catalog";
import { CartButton, useCart } from "../../cart";
import { ProductArtwork } from "../../product-art";
type Store={prices:Record<string,number>;productEdits:Record<string,{name:string;description:string}>;customProducts:(Product&{category:string})[]};
export default function ProductClient({category,productSlug}:{category:Category,productSlug:string}){
 const [selected,setSelected]=useState(0);const [stock,setStock]=useState<number>();const [store,setStore]=useState<Store>({prices:{},productEdits:{},customProducts:[]});const {add}=useCart();
 useEffect(()=>{fetch("/api/inventory",{cache:"no-store"}).then(r=>r.json()).then(v=>setStock(v[`${category.slug}/${productSlug}`])).catch(()=>{});fetch("/api/storefront",{cache:"no-store"}).then(r=>r.json()).then(setStore).catch(()=>{})},[category.slug,productSlug]);
 const baseProduct=[...category.products,...store.customProducts.filter(item=>item.category===category.slug)].find(item=>item.slug===productSlug);const product=baseProduct?{...baseProduct,...store.productEdits?.[`${category.slug}/${baseProduct.slug}`]}:undefined;
 if(!product)return <main className="product-page"><nav className="nav"><Link href="/" className="wordmark"><span>FR</span> FOREVERREPENT</Link></nav><section className="product-detail"><Link href={`/${category.slug}`} className="back">← {category.title}</Link><div className="detail-copy"><h1>Product unavailable.</h1></div></section></main>;
 const options=product.options.map((item,index)=>({...item,price:store.prices[`${category.slug}/${product.slug}/${index}`]??item.price}));const option=options[selected];const soldOut=stock===0;
 return <main className="product-page"><nav className="nav"><Link href="/" className="wordmark"><span>FR</span> FOREVERREPENT</Link><div className="nav-actions"><Link className="owner-link" href="/owner">Owner login</Link><CartButton/><a className="nav-discord" href="https://discord.gg/uynfPSkK8B" target="_blank">Join the server <b>↗</b></a></div></nav><section className="product-detail"><Link href={`/${category.slug}`} className="back">← {category.title}</Link><div className="detail-art"><ProductArtwork slug={product.slug} name={product.name} large/></div><div className="detail-copy"><p className="eyebrow">{category.kicker}</p><h1>{product.name}</h1><p>{product.description}</p><p className="warranty-note"><b>1-month warranty with vouch.</b><span>No vouch means the order is not covered by warranty.</span></p><p className={soldOut?"stock-state sold":"stock-state"}>{soldOut?"Sold out":stock===undefined?"Checking availability…":`${stock} currently in stock`}</p><div className="option-list">{options.map((item,index)=><button className={selected===index?"selected":""} onClick={()=>setSelected(index)} key={item.label}><span>{item.label}<small>{item.note||"Instant delivery"}</small></span><b>${item.price.toFixed(2)}</b></button>)}</div><button className="buy-button" disabled={soldOut} onClick={()=>add({id:`${category.slug}/${product.slug}/${option.label}`,name:product.name,option:option.label,price:option.price})}>{soldOut?"Sold out":<>Add to bag <span>${option.price.toFixed(2)} · ↗</span></>}</button><p className="delivery">Secured checkout · Instant delivery · Need help? <a href="https://discord.gg/uynfPSkK8B" target="_blank">Join the server</a></p></div></section></main>
}
