"use client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
type Item={id:string;name:string;option:string;unitPrice:number;quantity:number};type Message={id:number;sender:"customer"|"owner";body:string;createdAt:string};type Order={id:string;email:string;discordUsername:string;items:Item[];subtotal:number;status:string;createdAt:string;updatedAt:string;vouchedAt?:string;warrantyClaimedAt?:string};
export default function OrderView({id}:{id:string}){
 const [order,setOrder]=useState<Order>();const [messages,setMessages]=useState<Message[]>([]);const [body,setBody]=useState("");const [claim,setClaim]=useState("");const [copied,setCopied]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");
 const load=useCallback(async()=>{const response=await fetch(`/api/orders/${encodeURIComponent(id)}`,{cache:"no-store"});const data=await response.json();if(!response.ok){setError(data.error||"Order unavailable.");return}setOrder(data.order);setMessages(data.messages)},[id]);
 useEffect(()=>{load();const timer=setInterval(load,5000);return()=>clearInterval(timer)},[load]);
 const send=async(event:FormEvent)=>{event.preventDefault();if(!body.trim())return;const response=await fetch(`/api/orders/${encodeURIComponent(id)}/messages`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({body})});const data=await response.json();if(response.ok){setMessages(data.messages);setBody("")}else setError(data.error||"Message failed.")};
 const copyOrderId=async()=>{try{await navigator.clipboard.writeText(id);setCopied(true);window.setTimeout(()=>setCopied(false),2000)}catch{setError("Could not copy the Order ID. Press and hold it to copy.")}};
 const vouch=async()=>{const response=await fetch(`/api/orders/${encodeURIComponent(id)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"vouch"})});const data=await response.json();if(response.ok){setNotice("Vouch saved. Your one-month warranty is active.");await load()}else setNotice(data.error||"Could not save vouch.")};
 const warranty=async(event:FormEvent)=>{event.preventDefault();const response=await fetch(`/api/orders/${encodeURIComponent(id)}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"warranty",body:claim})});const data=await response.json();if(response.ok){setNotice("Warranty claim opened. The owner will reply in your private chat.");setClaim("");await load()}else setNotice(data.error||"Could not open warranty claim.")};
 if(error&&!order)return <main className="order-page"><section className="order-shell"><h1>Private order.</h1><p>{error}</p><Link href="/">← Return to storefront</Link></section></main>;
 if(!order)return <main className="order-page"><section className="order-shell"><p>Loading private order…</p></section></main>;
 return <main className="order-page"><nav className="nav"><Link href="/" className="wordmark"><span>FR</span> FOREVERREPENT</Link><b className="order-private">PRIVATE ORDER</b></nav><section className="order-shell"><header><div><p className="eyebrow">INVOICE / {order.id}</p><h1>Order <em>received.</em></h1><p>Contact us through the chat below to arrange manual Discord payment.</p></div><div className={`order-status ${order.status}`}>{order.status}</div></header><div className="invoice-card"><div className="invoice-meta"><span><small>Invoice</small>{order.id}</span><span><small>Email</small>{order.email}</span><span><small>Discord</small>{order.discordUsername||"Not provided"}</span><span><small>Created</small>{new Date(order.createdAt).toLocaleString()}</span></div>{order.items.map(item=><div className="invoice-line" key={`${item.id}/${item.option}`}><div><b>{item.name}</b><small>{item.option} · ×{item.quantity}</small></div><span>${(item.unitPrice*item.quantity).toFixed(2)}</span></div>)}<div className="invoice-total"><span>Total due</span><b>${order.subtotal.toFixed(2)}</b></div><div className="invoice-actions"><button className="invoice-print" onClick={copyOrderId}>{copied?"Order ID copied ✓":"Copy Order ID"}</button><button className="invoice-print" onClick={()=>window.print()}>Print / save invoice PDF</button></div></div>{order.status==="completed"&&<section className="warranty-center"><p className="eyebrow">VOUCH / WARRANTY CENTER</p><h2>Your coverage.</h2>{notice&&<p className="claim-notice">{notice}</p>}{!order.vouchedAt?<><p>Submit your vouch to activate one month of warranty coverage for this completed order.</p><button onClick={vouch}>I vouched · Activate warranty</button></>:<><p className="coverage-active">✓ Warranty activated {new Date(order.vouchedAt).toLocaleDateString()}</p>{order.warrantyClaimedAt?<p>Your warranty claim is open. Continue in the private support chat below.</p>:<form onSubmit={warranty}><textarea value={claim} onChange={event=>setClaim(event.target.value)} minLength={10} maxLength={1000} placeholder="Describe the product issue…" required/><button>Open warranty claim</button></form>}</>}</section>}<section className="order-chat"><div><p className="eyebrow">PRIVATE SUPPORT</p><h2>Chat with the owner.</h2></div><div className="messages">{messages.length===0?<p>No messages yet. Ask about payment or your order.</p>:messages.map(message=><article className={message.sender} key={message.id}><b>{message.sender==="owner"?"FOREVERREPENT":"YOU"}</b><p>{message.body}</p><small>{new Date(message.createdAt).toLocaleString()}</small></article>)}</div><form onSubmit={send}><textarea value={body} onChange={event=>setBody(event.target.value)} maxLength={2000} placeholder="Write a private message…" required/><button>Send message ↗</button></form></section></section></main>
}
